use_frameworks!

target 'GMDropTest_Example' do
  pod 'GM_Pod', :path => '../'

  target 'GMDropTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
